version: '3.4'

services:
  retros.web:
    image: retros
    build:
      context: ./app
    links:
      - "postgres:database"
    ports:
      - "5000:80"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty