version: '3.4'

services:
  retros.web:
    image: retros
    build:
      context: .
      dockerfile: app/Dockerfile
    links:
      - "postgres:database"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty