version: '3.4'

services:
  myretros.server:
    image: myretros.server
    build:
      context: ./server
    ports:
      - "5000:80"
    links:
      - "postgres:database"

  myretros.client:
    image: myretros.client
    build: 
        context: ./client
    ports:
       - "3000:80"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./postgres-data:/var/lib/postgresql/data